# Generated by Django 2.2.3 on 2019-07-09 03:37

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='', max_length=200)),
                ('descripcion', models.TextField(default='', max_length=5000)),
                ('comuna', models.CharField(default='', max_length=200)),
                ('direccion', models.CharField(default='', max_length=200)),
                ('latitud', models.DecimalField(decimal_places=99, default=0, max_digits=99, null=True)),
                ('longitud', models.DecimalField(decimal_places=99, default=0, max_digits=99, null=True)),
                ('estado', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('rut', models.CharField(default='', max_length=9)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
