# Generated by Django 2.2.3 on 2019-07-09 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190708_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lugar',
            name='latitud',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=90, null=True),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='longitud',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=90, null=True),
        ),
    ]
