# Generated by Django 2.2.3 on 2019-07-09 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190708_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='lugar',
            name='imagen',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
