# Generated by Django 2.2.3 on 2019-07-09 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190709_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lugar',
            name='imagen',
            field=models.ImageField(blank=True, default='', upload_to=''),
        ),
    ]
