# Generated by Django 2.2.3 on 2019-07-09 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190709_0230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_Lugar',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
