# Generated by Django 2.2.3 on 2019-07-10 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_lugar_tipo_lugar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lugar',
            name='imagen',
            field=models.CharField(blank=True, default='http://blogs.uladech.edu.pe/pastillasgerenciales/wp-content/uploads/sites/18/2016/08/error-code-18.jpeg', max_length=90000),
        ),
    ]
